name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y cmake ninja-build

      # Cache Google Test dependencies to prevent re-download on every run,
      # unless CMakeLists.txt changes.
      - name: Cache build dependencies
        uses: actions/cache@v4
        with:
          path: build/_deps
          key: deps-${{ hashFiles('CMakeLists.txt') }}

      - name: Run tests
        run: make test